# DigitalOcean App Platform Configuration

# .do/app.yaml - DigitalOcean App Platform
name: slotswapper
services:
- name: web
  source_dir: /
  github:
    repo: Diveshdk/slotswapper
    branch: main
  dockerfile_path: Dockerfile
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /api/health
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    type: SECRET
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    type: SECRET
  - key: SUPABASE_SERVICE_ROLE_KEY
    type: SECRET
  - key: SUPABASE_POSTGRES_URL
    type: SECRET
  - key: SUPABASE_POSTGRES_USER
    type: SECRET
  - key: SUPABASE_POSTGRES_HOST
    type: SECRET
  - key: SUPABASE_JWT_SECRET
    type: SECRET
  - key: SUPABASE_POSTGRES_PRISMA_URL
    type: SECRET
  - key: SUPABASE_POSTGRES_PASSWORD
    type: SECRET
  - key: SUPABASE_POSTGRES_DATABASE
    type: SECRET
  - key: SUPABASE_POSTGRES_URL_NON_POOLING
    type: SECRET

# Instructions for DigitalOcean deployment:
# 1. Create a DigitalOcean account
# 2. Go to App Platform
# 3. Create a new app from GitHub repository
# 4. Select your slotswapper repository
# 5. DigitalOcean will detect the Dockerfile
# 6. Configure environment variables as secrets
# 7. Deploy!
